name: Build and Run

on: push

env:
  OUTDIR: ./out
  N: 50

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x" # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: "x64" # optional x64 or x86. Defaults to x64 if not specified
      - name: Setup GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest
          platform: x64
      - name: Setup C++
        uses: kurocha/setup-cpp@v1
      - uses: actions/setup-java@v2
        with:
          distribution: "adopt" # See 'Supported distributions' for available options
          java-version: "8"
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
      - name: make all
        run: make all
